"""
CNN + Transformer Model Training Script
========================================
Trains the CNNTransformerPatternModel on synthetic chart pattern data.
Assumes dataset was generated by dataset_generator.py.

Usage:
    python -m training.train_cnn_transformer \
        --dataset-dir ./dataset \
        --output-dir  ./checkpoints \
        --epochs 50

Output: checkpoints/cnn_transformer_best.pt
"""

from __future__ import annotations

import argparse
import os
import time
import random
from pathlib import Path
from typing import Optional

import numpy as np

try:
    import torch
    import torch.nn as nn
    from torch.utils.data import Dataset, DataLoader
    TORCH_OK = True
except ImportError:
    TORCH_OK = False
    raise ImportError("PyTorch required: pip install torch==2.5.1")

try:
    from PIL import Image
    PIL_OK = True
except ImportError:
    PIL_OK = False

# ── Import model from services ─────────────────────────────────────────────

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.services.pattern_detection_service import (
    CNNTransformerPatternModel, PATTERNS
)


# ── Dataset ───────────────────────────────────────────────────────────────────

class ChartPatternDataset(Dataset):
    """
    Loads chart images from YOLO-style dataset directory.
    Converts image → 5-channel time-series proxy via colour gradients.
    For production, replace this with real OHLCV tensor loading.
    """

    def __init__(self, images_dir: str, labels_dir: str, seq_len: int = 64):
        self.seq_len = seq_len
        self.samples = []
        img_dir = Path(images_dir)
        lbl_dir = Path(labels_dir)
        for img_path in img_dir.glob("*.png"):
            lbl_path = lbl_dir / (img_path.stem + ".txt")
            if lbl_path.exists():
                class_id = int(lbl_path.read_text().split()[0])
                self.samples.append((img_path, class_id))
        random.shuffle(self.samples)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, class_id = self.samples[idx]
        # Convert image column pixels to 5-channel pseudo OHLCV
        if PIL_OK:
            img = Image.open(img_path).convert("L").resize((self.seq_len, 5))
            arr = np.array(img, dtype=np.float32) / 255.0  # (5, seq_len)
        else:
            arr = np.zeros((5, self.seq_len), dtype=np.float32)
        x = torch.tensor(arr)  # (5, seq_len)
        y = torch.tensor(class_id, dtype=torch.long)
        return x, y


# ── Training Loop ─────────────────────────────────────────────────────────────

def train(dataset_dir: str, output_dir: str, epochs: int = 50,
          batch_size: int = 32, lr: float = 3e-4, seq_len: int = 64):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on: {device}")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # ── Datasets ────────────────────────────────────────────────────────────
    train_ds = ChartPatternDataset(
        f"{dataset_dir}/images/train",
        f"{dataset_dir}/labels/train",
        seq_len=seq_len,
    )
    val_ds = ChartPatternDataset(
        f"{dataset_dir}/images/val",
        f"{dataset_dir}/labels/val",
        seq_len=seq_len,
    )
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                              num_workers=2, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=batch_size,
                              num_workers=2)

    print(f"Train: {len(train_ds)} | Val: {len(val_ds)}")

    # ── Model ───────────────────────────────────────────────────────────────
    model = CNNTransformerPatternModel(n_classes=len(PATTERNS), seq_len=seq_len)
    model = model.to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

    best_val_acc = 0.0
    best_path    = out / "cnn_transformer_best.pt"

    for epoch in range(1, epochs + 1):
        # ── Train ──────────────────────────────────────────────────────────
        model.train()
        train_loss = train_correct = train_total = 0
        t0 = time.time()
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            logits = model(x)
            loss = criterion(logits, y)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_loss    += loss.item() * len(y)
            train_correct += (logits.argmax(1) == y).sum().item()
            train_total   += len(y)
        scheduler.step()

        # ── Validate ───────────────────────────────────────────────────────
        model.eval()
        val_correct = val_total = 0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                logits    = model(x)
                val_correct += (logits.argmax(1) == y).sum().item()
                val_total   += len(y)

        train_acc = train_correct / max(train_total, 1) * 100
        val_acc   = val_correct   / max(val_total,   1) * 100
        elapsed   = time.time() - t0

        print(f"Epoch {epoch:3d}/{epochs} | "
              f"loss={train_loss/max(train_total,1):.4f} | "
              f"train_acc={train_acc:.1f}% | val_acc={val_acc:.1f}% | "
              f"t={elapsed:.1f}s")

        # ── Checkpoint ────────────────────────────────────────────────────
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), best_path)
            print(f"  ✓ New best saved: {best_path} (val_acc={val_acc:.1f}%)")

    print(f"\nTraining complete. Best val accuracy: {best_val_acc:.1f}%")
    print(f"Best model: {best_path}")
    return str(best_path)


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset-dir",  default="./dataset",     type=str)
    parser.add_argument("--output-dir",   default="./checkpoints", type=str)
    parser.add_argument("--epochs",       default=50,              type=int)
    parser.add_argument("--batch-size",   default=32,              type=int)
    parser.add_argument("--lr",           default=3e-4,            type=float)
    parser.add_argument("--seq-len",      default=64,              type=int)
    args = parser.parse_args()

    train(args.dataset_dir, args.output_dir, args.epochs,
          args.batch_size, args.lr, args.seq_len)
